name: PCDS Standard Testing

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/pre-commit.yml@d535ae04c63236687160bfde064e83489a5eceba
